# Uncomment the next line to define a global platform for your project
platform :ios, '14.1.0'
target 'EnTransparencia' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  
  pod 'GoogleMaps', '4.2.0'
  
end
